{% set name = "rio-viz" %}
{% set version = "0.9.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rio-viz-{{ version }}.tar.gz
  sha256: 55449e3a604c117e0bf5443e6417a459e2403364eb932c8da774b01a41b5bdd6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - braceexpand
    - python >=3.6
    - rio-cogeo >=2.2,<3.0
    - rio-tiler >=2.1,<3.0
    - titiler-core >=0.3.10,<0.4
    - uvicorn

test:
  imports:
    - rio_viz
    - rio_viz.io
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/developmentseed/rio-viz
  summary: Visualize Cloud Optimized GeoTIFF in browser
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rsignell-usgs
